# Generated by Django 3.2.17 on 2023-02-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230216_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. Of Guests'),
        ),
    ]
