# Generated by Django 3.2.17 on 2023-02-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_number_of_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_guests',
        ),
    ]
