# Generated by Django 3.2.17 on 2023-02-16 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_number_of_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_guests',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='No. Of Guests(Max = 12)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='No. Of Guests'),
        ),
    ]
