# Generated by Django 3.2.17 on 2023-02-16 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20230216_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='timeslot',
            field=models.IntegerField(choices=[(1, '10:00 – 11:00'), (2, '11:00 – 12:00'), (3, '12:00 – 13:00'), (4, '13:00 – 14:00'), (5, '14:00 – 15:00'), (6, '15:00 – 16:00'), (7, '16:00 – 17:00'), (8, '17:00 – 18:00'), (8, '18:00 – 19:00')], default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_guests',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='No. Of Guests(Max = 12)'),
        ),
    ]
